name: Convert to Issue

on:
  issues:
    types: [opened]

jobs:
  set-issue-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Issue with Template
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --body "$(cat .github/ISSUE_TEMPLATE/exploration-project.md)"
